import json
import os
import boto3
from decimal import Decimal

ddb = boto3.resource('dynamodb')
table = ddb.Table(os.environ['AGENT_TABLE_NAME'])

SEED_DATA = [
    # Grid Operations (7)
    # Grid Operations (7) — RAI scores computed by rai-scorer Lambda
    {"agentId": "grid-stability-monitor", "name": "Grid Stability Monitor", "system": "GE ADMS", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 8712, "errors": 12, "avgResponseMs": 85, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("892"), "costPerInvocation": Decimal("0.0003"), "utilization": 94},
    {"agentId": "demand-forecast", "name": "Demand Forecast Agent", "system": "AVEVA Pi Historian", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 6234, "errors": 18, "avgResponseMs": 142, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("645"), "costPerInvocation": Decimal("0.0008"), "utilization": 88},
    {"agentId": "renewable-dispatch", "name": "Renewable Dispatch Optimizer", "system": "GE ADMS", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 4890, "errors": 9, "avgResponseMs": 198, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("467"), "costPerInvocation": Decimal("0.0006"), "utilization": 86},
    {"agentId": "load-balancing", "name": "Load Balancing Agent", "system": "GE ADMS", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 7456, "errors": 21, "avgResponseMs": 67, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("534"), "costPerInvocation": Decimal("0.0004"), "utilization": 91},
    {"agentId": "frequency-regulation", "name": "Frequency Regulation Agent", "system": "Survalent SCADA", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 12450, "errors": 8, "avgResponseMs": 34, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("723"), "costPerInvocation": Decimal("0.0002"), "utilization": 96},
    {"agentId": "voltage-optimization", "name": "Voltage Optimization Agent", "system": "GE ADMS", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 5678, "errors": 14, "avgResponseMs": 112, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("398"), "costPerInvocation": Decimal("0.0005"), "utilization": 79},
    {"agentId": "outage-prediction", "name": "Outage Prediction Agent", "system": "GE ADMS", "category": "Grid Operations", "platform": "native", "status": "active", "requests": 3201, "errors": 7, "avgResponseMs": 245, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("412"), "costPerInvocation": Decimal("0.0009"), "utilization": 78},
    # Asset Management (6)
    {"agentId": "pipeline-integrity", "name": "Pipeline Integrity Agent", "system": "Maximo", "category": "Asset Management", "platform": "native", "status": "active", "requests": 2156, "errors": 5, "avgResponseMs": 380, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("356"), "costPerInvocation": Decimal("0.0004"), "utilization": 71},
    {"agentId": "transformer-health", "name": "Transformer Health Agent", "system": "AVEVA Pi Historian", "category": "Asset Management", "platform": "native", "status": "active", "requests": 1890, "errors": 3, "avgResponseMs": 420, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("312"), "costPerInvocation": Decimal("0.0007"), "utilization": 68},
    {"agentId": "turbine-performance", "name": "Turbine Performance Agent", "system": "Maximo", "category": "Asset Management", "platform": "native", "status": "active", "requests": 2345, "errors": 11, "avgResponseMs": 310, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("287"), "costPerInvocation": Decimal("0.0005"), "utilization": 64},
    {"agentId": "vegetation-management", "name": "Vegetation Management Agent", "system": "Esri ArcGIS", "category": "Asset Management", "platform": "native", "status": "active", "requests": 876, "errors": 4, "avgResponseMs": 520, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("178"), "costPerInvocation": Decimal("0.0005"), "utilization": 52},
    {"agentId": "substation-monitor", "name": "Substation Monitor", "system": "Survalent SCADA", "category": "Asset Management", "platform": "native", "status": "active", "requests": 9870, "errors": 16, "avgResponseMs": 56, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("621"), "costPerInvocation": Decimal("0.0002"), "utilization": 89},
    {"agentId": "predictive-maintenance", "name": "Predictive Maintenance Agent", "system": "Maximo", "category": "Asset Management", "platform": "native", "status": "active", "requests": 1563, "errors": 8, "avgResponseMs": 380, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("245"), "costPerInvocation": Decimal("0.0006"), "utilization": 61},
    # Trading & Markets (5)
    {"agentId": "energy-trading", "name": "Energy Trading Agent", "system": "Databricks", "category": "Trading & Markets", "platform": "native", "status": "active", "requests": 1095, "errors": 5, "avgResponseMs": 190, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("578"), "costPerInvocation": Decimal("0.0012"), "utilization": 82},
    {"agentId": "price-forecast", "name": "Price Forecast Agent", "system": "Snowflake", "category": "Trading & Markets", "platform": "native", "status": "active", "requests": 2890, "errors": 6, "avgResponseMs": 340, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("445"), "costPerInvocation": Decimal("0.0007"), "utilization": 76},
    {"agentId": "congestion-management", "name": "Congestion Management Agent", "system": "Oracle EDW", "category": "Trading & Markets", "platform": "native", "status": "active", "requests": 1456, "errors": 3, "avgResponseMs": 275, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("334"), "costPerInvocation": Decimal("0.0006"), "utilization": 69},
    {"agentId": "capacity-planning", "name": "Capacity Planning Agent", "system": "Databricks", "category": "Trading & Markets", "platform": "native", "status": "active", "requests": 987, "errors": 2, "avgResponseMs": 450, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("267"), "costPerInvocation": Decimal("0.0008"), "utilization": 58},
    {"agentId": "hedging-strategy", "name": "Hedging Strategy Agent", "system": "Snowflake", "category": "Trading & Markets", "platform": "native", "status": "active", "requests": 654, "errors": 1, "avgResponseMs": 380, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("198"), "costPerInvocation": Decimal("0.0009"), "utilization": 54},
    # Safety & Compliance (6)
    {"agentId": "scada-anomaly", "name": "SCADA Anomaly Detector", "system": "Netskope", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 8920, "errors": 23, "avgResponseMs": 45, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("523"), "costPerInvocation": Decimal("0.0002"), "utilization": 91},
    {"agentId": "emissions-tracking", "name": "Emissions Tracking Agent", "system": "Security Lake", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 4567, "errors": 6, "avgResponseMs": 290, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("289"), "costPerInvocation": Decimal("0.0003"), "utilization": 65},
    {"agentId": "safety-incident", "name": "Safety Incident Agent", "system": "Security Lake", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 3456, "errors": 2, "avgResponseMs": 180, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("256"), "costPerInvocation": Decimal("0.0004"), "utilization": 72},
    {"agentId": "regulatory-filing", "name": "Regulatory Filing Agent", "system": "Security Lake", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 987, "errors": 1, "avgResponseMs": 520, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("189"), "costPerInvocation": Decimal("0.0007"), "utilization": 55},
    {"agentId": "meter-data-validator", "name": "Meter Data Validator", "system": "Itron AMI", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 15670, "errors": 15, "avgResponseMs": 32, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("234"), "costPerInvocation": Decimal("0.0001"), "utilization": 73},
    {"agentId": "compliance-auditor", "name": "Compliance Auditor", "system": "Security Lake", "category": "Safety & Compliance", "platform": "native", "status": "active", "requests": 2340, "errors": 4, "avgResponseMs": 410, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("213"), "costPerInvocation": Decimal("0.0005"), "utilization": 67},
    # Customer Operations (6)
    {"agentId": "billing-reconciliation", "name": "Billing Reconciliation Agent", "system": "Oracle CIS", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 4102, "errors": 15, "avgResponseMs": 310, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("378"), "costPerInvocation": Decimal("0.0005"), "utilization": 74},
    {"agentId": "demand-response", "name": "Demand Response Agent", "system": "Oracle CIS", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 2340, "errors": 8, "avgResponseMs": 220, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("298"), "costPerInvocation": Decimal("0.0006"), "utilization": 70},
    {"agentId": "customer-usage", "name": "Customer Usage Analyzer", "system": "Itron AMI", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 6789, "errors": 12, "avgResponseMs": 165, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("345"), "costPerInvocation": Decimal("0.0003"), "utilization": 77},
    {"agentId": "outage-communication", "name": "Outage Communication Agent", "system": "Amazon Connect", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 3456, "errors": 5, "avgResponseMs": 140, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("267"), "costPerInvocation": Decimal("0.0004"), "utilization": 75},
    {"agentId": "ev-charging", "name": "EV Charging Optimizer", "system": "DERMS", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 5670, "errors": 9, "avgResponseMs": 195, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("389"), "costPerInvocation": Decimal("0.0004"), "utilization": 81},
    {"agentId": "customer-meter-validator", "name": "Meter Data Validator", "system": "Landis+Gyr AMI", "category": "Customer Operations", "platform": "native", "status": "active", "requests": 8901, "errors": 10, "avgResponseMs": 28, "score": 0, "fairness": 0, "transparency": 0, "accountability": 0, "ethics": 0, "monthlyCost": Decimal("156"), "costPerInvocation": Decimal("0.0001"), "utilization": 70},
]

COMPLIANCE_DATA = [
    {"agentId": "compliance:nerc-cip", "name": "NERC CIP", "complianceScore": Decimal("96"), "status": "compliant", "lastAudit": "2/10/2026", "controls": '[{"n":"Electronic Security","s":97},{"n":"Physical Security","s":95},{"n":"Incident Response","s":96},{"n":"Recovery Plans","s":94}]'},
    {"agentId": "compliance:ferc", "name": "FERC Standards", "complianceScore": Decimal("93"), "status": "compliant", "lastAudit": "1/15/2026", "controls": '[{"n":"Market Transparency","s":95},{"n":"Rate Compliance","s":92},{"n":"Reliability Standards","s":93}]'},
    {"agentId": "compliance:epa", "name": "EPA Emissions", "complianceScore": Decimal("89"), "status": "warning", "lastAudit": "12/20/2025", "controls": '[{"n":"CO2 Reporting","s":91},{"n":"Methane Monitoring","s":86},{"n":"Leak Detection","s":88}]'},
    {"agentId": "compliance:iso55001", "name": "ISO 55001", "complianceScore": Decimal("94"), "status": "compliant", "lastAudit": "1/28/2026", "controls": '[{"n":"Asset Planning","s":95},{"n":"Lifecycle Management","s":93},{"n":"Performance Evaluation","s":94}]'},
    {"agentId": "compliance:soc2", "name": "SOC 2 Type II", "complianceScore": Decimal("92"), "status": "compliant", "lastAudit": "11/30/2025", "controls": '[{"n":"Security","s":94},{"n":"Availability","s":91},{"n":"Confidentiality","s":92}]'},
    {"agentId": "compliance:doe-cyber", "name": "DOE Cybersecurity", "complianceScore": Decimal("88"), "status": "warning", "lastAudit": "1/5/2026", "controls": '[{"n":"OT Security","s":90},{"n":"Supply Chain Risk","s":85},{"n":"Incident Reporting","s":87}]'},
    {"agentId": "compliance:nist-govern", "name": "NIST AI RMF - Govern", "complianceScore": Decimal("91"), "status": "compliant", "lastAudit": "2/18/2026", "controls": '[{"n":"Governance Structure","s":93},{"n":"Risk Tolerance","s":90},{"n":"Accountability Mechanisms","s":91},{"n":"Organizational Policies","s":89}]'},
    {"agentId": "compliance:nist-map", "name": "NIST AI RMF - Map", "complianceScore": Decimal("88"), "status": "warning", "lastAudit": "2/18/2026", "controls": '[{"n":"Context & Use Case Mapping","s":90},{"n":"Stakeholder Identification","s":87},{"n":"Benefit/Risk Framing","s":86},{"n":"Interdependency Analysis","s":88}]'},
    {"agentId": "compliance:nist-measure", "name": "NIST AI RMF - Measure", "complianceScore": Decimal("90"), "status": "compliant", "lastAudit": "2/18/2026", "controls": '[{"n":"Bias & Fairness Metrics","s":92},{"n":"Reliability Testing","s":91},{"n":"Explainability Assessment","s":88},{"n":"Privacy Risk Quantification","s":89}]'},
    {"agentId": "compliance:nist-manage", "name": "NIST AI RMF - Manage", "complianceScore": Decimal("87"), "status": "warning", "lastAudit": "2/18/2026", "controls": '[{"n":"Risk Prioritization","s":89},{"n":"Mitigation Strategies","s":86},{"n":"Continuous Monitoring","s":88},{"n":"Incident Response for AI","s":84}]'},
    {"agentId": "compliance:nist-sp800-37", "name": "NIST SP 800-37 (RMF)", "complianceScore": Decimal("89"), "status": "warning", "lastAudit": "3/15/2026", "controls": '[{"n":"Prepare - Risk Context & Priorities","s":92},{"n":"Categorize - System Impact Level","s":91},{"n":"Select - Security Controls (SP 800-53)","s":88},{"n":"Implement - Control Deployment","s":90},{"n":"Assess - Control Effectiveness","s":87},{"n":"Authorize - Risk Acceptance Decision","s":85},{"n":"Monitor - Continuous Posture Tracking","s":91}]'},
]

AOP_DATA = [
    {"agentId": "aop:AOP-E01", "aopId": "AOP-E01", "name": "Grid Frequency Deviation Response", "status": "active", "agents": "Grid Stability Monitor, Frequency Regulation Agent", "executions": 12450, "successRate": Decimal("97.8"), "owner": "Grid Operations", "entry": "Grid frequency deviates beyond +/-0.03 Hz from 60.00 Hz target"},
    {"agentId": "aop:AOP-E02", "aopId": "AOP-E02", "name": "Renewable Curtailment Optimization", "status": "active", "agents": "Renewable Dispatch Optimizer, Demand Forecast Agent", "executions": 3890, "successRate": Decimal("95.2"), "owner": "Grid Operations", "entry": "Forecasted renewable generation exceeds demand + transmission capacity"},
    {"agentId": "aop:AOP-E03", "aopId": "AOP-E03", "name": "SCADA Intrusion Detection", "status": "active", "agents": "SCADA Anomaly Detector, Safety Incident Agent", "executions": 8920, "successRate": Decimal("99.1"), "owner": "OT Security", "entry": "Anomalous network traffic pattern detected on OT network"},
    {"agentId": "aop:AOP-E04", "aopId": "AOP-E04", "name": "Transformer Health Assessment", "status": "active", "agents": "Transformer Health Agent, Predictive Maintenance Agent", "executions": 2156, "successRate": Decimal("94.5"), "owner": "Asset Management", "entry": "Scheduled DGA reading received or thermal alert triggered"},
    {"agentId": "aop:AOP-E05", "aopId": "AOP-E05", "name": "Day-Ahead Energy Bidding", "status": "active", "agents": "Energy Trading Agent, Price Forecast Agent", "executions": 1095, "successRate": Decimal("93.8"), "owner": "Trading Desk", "entry": "Daily trigger at T-14h before operating day gate closure"},
    {"agentId": "aop:AOP-E06", "aopId": "AOP-E06", "name": "Methane Leak Detection & Response", "status": "active", "agents": "Emissions Tracking Agent, Pipeline Integrity Agent", "executions": 4567, "successRate": Decimal("96.3"), "owner": "Environmental", "entry": "Methane concentration reading exceeds EPA threshold at any sensor"},
    {"agentId": "aop:AOP-E07", "aopId": "AOP-E07", "name": "Storm Outage Prediction & Staging", "status": "active", "agents": "Outage Prediction Agent, Vegetation Management Agent", "executions": 876, "successRate": Decimal("91.4"), "owner": "Emergency Mgmt", "entry": "NWS issues severe weather watch for service territory"},
    {"agentId": "aop:AOP-E08", "aopId": "AOP-E08", "name": "Demand Response Event Dispatch", "status": "active", "agents": "Demand Response Agent, Customer Usage Analyzer", "executions": 2340, "successRate": Decimal("94.9"), "owner": "Customer Operations", "entry": "Grid stress index exceeds DR activation threshold"},
    {"agentId": "aop:AOP-E09", "aopId": "AOP-E09", "name": "Pipeline Integrity Inline Inspection", "status": "active", "agents": "Pipeline Integrity Agent, Safety Incident Agent", "executions": 312, "successRate": Decimal("97.1"), "owner": "Pipeline Operations", "entry": "Scheduled inline inspection run or integrity alert triggered"},
    {"agentId": "aop:AOP-E10", "aopId": "AOP-E10", "name": "EV Charging Load Management", "status": "active", "agents": "EV Charging Optimizer, Load Balancing Agent", "executions": 5670, "successRate": Decimal("95.7"), "owner": "Customer Operations", "entry": "Aggregate EV charging load exceeds 70% of allocated distribution capacity"},
    {"agentId": "aop:AOP-E11", "aopId": "AOP-E11", "name": "Carbon Credit Portfolio Optimization", "status": "draft", "agents": "Emissions Tracking Agent, Hedging Strategy Agent", "executions": 0, "successRate": Decimal("0"), "owner": "Sustainability", "entry": "Quarterly emissions reconciliation deadline approaching"},
    {"agentId": "aop:AOP-E12", "aopId": "AOP-E12", "name": "Microgrid Islanding Automation", "status": "draft", "agents": "Grid Stability Monitor, Renewable Dispatch Optimizer", "executions": 0, "successRate": Decimal("0"), "owner": "Distributed Energy", "entry": "Grid disturbance detected at microgrid point of common coupling"},
    {"agentId": "aop:AOP-E13", "aopId": "AOP-E13", "name": "Wildfire Risk Powerline De-energization", "status": "review", "agents": "Vegetation Management Agent, Outage Prediction Agent, Safety Incident Agent", "executions": 45, "successRate": Decimal("88.9"), "owner": "Public Safety", "entry": "Fire weather watch or red flag warning issued for service territory"},
    {"agentId": "aop:AOP-E14", "aopId": "AOP-E14", "name": "Nuclear Plant Coolant Monitoring", "status": "review", "agents": "SCADA Anomaly Detector, Safety Incident Agent", "executions": 128, "successRate": Decimal("100"), "owner": "Nuclear Operations", "entry": "Coolant loop parameter deviates from normal operating band"},
]

ACCESS_DATA = [
    {"agentId": "access:rachel-torres", "userName": "Rachel Torres", "role": "Grid Operations Director", "accessLevel": "admin", "gridOps": "full", "assetMgmt": "full", "trading": "read", "safety": "full", "customer": "read"},
    {"agentId": "access:mark-sullivan", "userName": "Mark Sullivan", "role": "CISO - OT Security", "accessLevel": "admin", "gridOps": "audit", "assetMgmt": "audit", "trading": "audit", "safety": "full", "customer": "audit"},
    {"agentId": "access:anika-patel", "userName": "Anika Patel", "role": "ML Engineer - Grid AI", "accessLevel": "engineer", "gridOps": "exec", "assetMgmt": "exec", "trading": "read", "safety": "exec", "customer": "read"},
    {"agentId": "access:tom-nguyen", "userName": "Tom Nguyen", "role": "SCADA Engineer", "accessLevel": "engineer", "gridOps": "full", "assetMgmt": "exec", "trading": "none", "safety": "full", "customer": "none"},
    {"agentId": "access:karen-mitchell", "userName": "Karen Mitchell", "role": "Regulatory Affairs", "accessLevel": "viewer", "gridOps": "read", "assetMgmt": "read", "trading": "read", "safety": "audit", "customer": "read"},
    {"agentId": "access:david-chen", "userName": "David Chen", "role": "Energy Trader", "accessLevel": "viewer", "gridOps": "read", "assetMgmt": "none", "trading": "full", "safety": "none", "customer": "read"},
]

def handler(event, context):
    request_type = event.get('RequestType', '')
    physical_id = event.get('PhysicalResourceId', context.log_stream_name)
    if request_type in ('Create', 'Update'):
        with table.batch_writer() as batch:
            for item in SEED_DATA:
                batch.put_item(Item=item)
            for item in COMPLIANCE_DATA + AOP_DATA + ACCESS_DATA:
                batch.put_item(Item=item)
    return {'PhysicalResourceId': physical_id}
